server:
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true

spring:
  application:
    name: pet_health
  profiles:
    active: dev  # 激活dev环境

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml  # Mapper XML 文件路径（如有）
  type-enums-package: org.project.pet_health.enums
  type-aliases-package: org.project.pet_health.entity  # 实体类包路径（替换成你的实际路径）
  configuration:
    map-underscore-to-camel-case: true  # 下划线自动转驼峰（必开）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印 SQL 日志（开发用）
  global-config:
      # 全局配置
    db-config:
        # 数据库配置
      id-type: auto

# 微信小程序配置
wechat:
  miniapp:
    appid: "wx7d92a25954cc0513" # 替换成你自己的真实 AppID
    secret: "c377e2bd55b86a244044e6c6cec96ade" # 替换成你自己的真实 AppSecret


#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志

deepseek:
  api-key: sk-16bf97fd32cf45c088c4386aa97e0b5b
  api-url: https://api.deepseek.com/chat/completions
  model: deepseek-chat
